import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { AgentLoopReporter } from '../agent/AgentLoopReporter.js';
import { AgentLoopStateStore } from '../agent/AgentLoopStateStore.js';
import { AgentRuntimeBridge } from '../agent/AgentRuntimeBridge.js';
import { AgentStepExecutor } from '../agent/AgentStepExecutor.js';
import { InteractiveAgentLoop } from '../agent/InteractiveAgentLoop.js';
import type { AgentLoopState } from '../agent/AgentTypes.js';
import type {
  CliGitCommand,
  CliInspectCommand,
  CliRepairCommand,
  CliValidateCommand,
} from '../cli/CliTypes.js';

function assert(condition: boolean, message: string): void {
  if (!condition) {
    throw new Error(message);
  }
}

class RecordingCliBridge {
  public repairCommands: CliRepairCommand[] = [];

  public inspect(command: CliInspectCommand): Promise<unknown> {
    return Promise.resolve({
      status: 'ok',
      inspection: {
        projectRoot: command.projectRoot,
        configInfo: {
          detectedStack: ['typescript'],
        },
        targetFiles: command.targetFiles.map((relativePath) => {
          return {
            relativePath,
            exists: true,
            bytes: 24,
            extension: '.ts',
          };
        }),
      },
    });
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  public validate(_command: CliValidateCommand): Promise<unknown> {
    return Promise.resolve({
      status: 'ok',
      validation: {
        status: 'passed',
        commands: [],
        findings: [],
      },
    });
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  public git(_command: CliGitCommand): Promise<unknown> {
    return Promise.resolve({
      action: 'doctor',
      boundary: {
        branch: 'test-branch',
        workingTreeState: 'clean',
      },
      guard: {
        decision: 'allowed',
        allowed: true,
      },
    });
  }

  public repair(command: CliRepairCommand): Promise<unknown> {
    this.repairCommands.push(command);

    return Promise.resolve({
      id: 'agent-provider-runtime-flow-repair-attempt',
      status: 'proposal_ready',
      objective: command.objective,
      projectRoot: command.projectRoot,
      proposal: {
        id: 'agent-provider-runtime-flow-proposal',
        summary: 'Runtime-flow fake repair proposal.',
        riskLevel: 'low',
        operations: [
          {
            kind: 'replace_file',
            targetFile: 'src/index.ts',
            expectedCurrentContent: 'export const value = 1;\n',
            newContent: 'export const value = 1;\n',
            reason: 'Deterministic no-op proposal for provider runtime flow.',
          },
        ],
        explanation: 'This proposal is generated by the recording bridge test double.',
      },
      patchValidation: {
        valid: true,
        issues: [],
      },
      diffPreviews: [
        {
          targetFile: 'src/index.ts',
          changed: false,
          changedLines: 0,
          markdown: '',
        },
      ],
      modelPolicyDecision: {
        status: 'allowed',
        selectedProvider: command.provider,
        selectedModel: command.providerModel ?? 'fake-llm/test-model',
      },
      providerFallbackUsed: command.provider !== 'openrouter',
    });
  }
}

async function main(): Promise<void> {
  const fixtureRoot = resolve('.runtime/agent-provider-runtime-flow-test/project');
  const runtimeRoot = resolve(fixtureRoot, '.runtime');
  const statePath = resolve(runtimeRoot, 'agent-loop-state.json');
  const reportPath = resolve(runtimeRoot, 'agent-loop-report.md');
  const targetFile = 'src/index.ts';

  await resetFixture(fixtureRoot);

  const store = new AgentLoopStateStore({
    outputPath: statePath,
  });

  const reporter = new AgentLoopReporter({
    outputPath: reportPath,
  });

  const recordingBridge = new RecordingCliBridge();

  const executor = new AgentStepExecutor({
    runtimeBridge: new AgentRuntimeBridge({
      cliBridge: recordingBridge,
    }),
    store,
    reporter,
  });

  const loop = new InteractiveAgentLoop({
    store,
    reporter,
  });

  let state = await loop.start({
    objective: 'Validate agent provider runtime flow without real provider call.',
    projectRoot: fixtureRoot,
    projectName: 'Agent Provider Runtime Flow Fixture',
    targetFiles: [targetFile],
    metadata: {
      provider: 'openrouter',
      fakeProviderMode: 'markdown_json',
      providerModel: 'poolside/laguna-xs.2:free',
      estimatedCompletionTokens: 1200,
      allowRealProvider: true,
      allowPremium: false,
      premiumApproved: false,
      includeProjectMemory: true,
    },
  });

  state = await executor.execute(state, 'agent-action-request_repair_proposal');

  assert(
    recordingBridge.repairCommands.length === 1,
    'Expected exactly one repair command to be recorded.',
  );

  const repairCommand = requireRepairCommand(recordingBridge);

  assert(
    repairCommand.provider === 'openrouter',
    'Agent repair proposal step should pass OpenRouter provider when policy allows it.',
  );
  assert(
    repairCommand.providerModel === 'poolside/laguna-xs.2:free',
    'Agent repair proposal step should pass persisted provider model.',
  );
  assert(
    repairCommand.allowRealProvider === true,
    'Agent repair proposal step should preserve allowRealProvider.',
  );
  assert(
    repairCommand.includeProjectMemory === true,
    'Agent repair proposal step should preserve includeProjectMemory.',
  );
  assert(
    repairCommand.estimatedCompletionTokens === 1200,
    'Agent repair proposal step should pass estimated completion tokens.',
  );
  assert(
    repairCommand.allowPremium === false,
    'Free OpenRouter model should not imply premium allowance.',
  );
  assert(
    repairCommand.premiumApproved === false,
    'Free OpenRouter model should not imply premium approval.',
  );

  const repairExecution = getMetadataObject(state, 'execution_request_repair_proposal');
  const providerAudit = getNestedObject(repairExecution, 'agentProviderAudit');

  assert(
    providerAudit['policyStatus'] === 'allowed',
    'Repair execution metadata should include allowed provider policy status.',
  );
  assert(
    providerAudit['requestedProvider'] === 'openrouter',
    'Provider audit should include requested OpenRouter provider.',
  );
  assert(
    providerAudit['selectedProvider'] === 'openrouter',
    'Provider audit should include selected OpenRouter provider.',
  );
  assert(
    providerAudit['selectedModel'] === 'poolside/laguna-xs.2:free',
    'Provider audit should include selected model.',
  );
  assert(
    providerAudit['allowRealProvider'] === true,
    'Provider audit should include real provider opt-in.',
  );

  const applyAction = state.actions.find((action) => action.id === 'agent-action-apply_patch');

  assert(
    applyAction?.status === 'pending',
    'Provider proposal step must not execute or approve apply_patch.',
  );
  assert(state.approvals.length === 0, 'Provider proposal step must not create approval requests.');

  const stateRaw = await readFile(statePath, 'utf8');
  const reportRaw = await readFile(reportPath, 'utf8');

  assert(
    stateRaw.includes('"agentProviderAudit"'),
    'Persisted agent state should include agentProviderAudit.',
  );
  assert(
    stateRaw.includes('"selectedProvider": "openrouter"'),
    'Persisted agent state should include selected OpenRouter provider.',
  );
  assert(
    reportRaw.includes('Provider: openrouter'),
    'Agent report should include provider config.',
  );
  assert(
    reportRaw.includes('Provider model: poolside/laguna-xs.2:free'),
    'Agent report should include provider model.',
  );

  const blockedRecordingBridge = new RecordingCliBridge();
  const blockedExecutor = new AgentStepExecutor({
    runtimeBridge: new AgentRuntimeBridge({
      cliBridge: blockedRecordingBridge,
    }),
    store,
    reporter,
  });

  let blockedState = await loop.start({
    id: 'agent-provider-runtime-flow-blocked-loop',
    objective: 'Validate blocked OpenRouter fallback.',
    projectRoot: fixtureRoot,
    projectName: 'Agent Provider Runtime Flow Blocked Fixture',
    targetFiles: [targetFile],
    metadata: {
      provider: 'openrouter',
      fakeProviderMode: 'markdown_json',
      providerModel: 'poolside/laguna-xs.2:free',
      estimatedCompletionTokens: 1200,
      allowRealProvider: false,
      allowPremium: false,
      premiumApproved: false,
      includeProjectMemory: true,
    },
  });

  blockedState = await blockedExecutor.execute(
    blockedState,
    'agent-action-request_repair_proposal',
  );

  const blockedRepairCommand = requireRepairCommand(blockedRecordingBridge);

  assert(
    blockedRepairCommand.provider === 'fake-llm',
    'Blocked OpenRouter config should fallback to fake-llm during agent repair proposal step.',
  );
  assert(
    blockedRepairCommand.allowRealProvider === false,
    'Fallback repair command must not allow real provider.',
  );

  const blockedRepairExecution = getMetadataObject(
    blockedState,
    'execution_request_repair_proposal',
  );
  const blockedProviderAudit = getNestedObject(blockedRepairExecution, 'agentProviderAudit');

  assert(
    blockedProviderAudit['policyStatus'] === 'blocked',
    'Blocked repair execution metadata should include blocked provider policy status.',
  );
  assert(
    blockedProviderAudit['selectedProvider'] === 'fake-llm',
    'Blocked provider audit should select fake fallback.',
  );
  assert(
    blockedProviderAudit['fallbackReason'] !== undefined,
    'Blocked provider audit should include fallback reason.',
  );

  console.info(
    JSON.stringify(
      {
        status: 'ok',
        test: 'agent-provider-runtime-flow-test',
        checked: {
          allowedProvider: repairCommand.provider,
          blockedProvider: blockedRepairCommand.provider,
          auditStatus: providerAudit['policyStatus'],
          blockedAuditStatus: blockedProviderAudit['policyStatus'],
        },
      },
      null,
      2,
    ),
  );
}

function requireRepairCommand(bridge: RecordingCliBridge): CliRepairCommand {
  const command = bridge.repairCommands[0];

  if (!command) {
    throw new Error('Expected repair command to be recorded.');
  }

  return command;
}

function getMetadataObject(state: AgentLoopState, key: string): Record<string, unknown> {
  const value = state.metadata?.[key];

  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`Expected metadata object: ${key}`);
  }

  return value;
}

function getNestedObject(record: Record<string, unknown>, key: string): Record<string, unknown> {
  const value = record[key];

  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`Expected nested object: ${key}`);
  }

  return value as Record<string, unknown>;
}

async function resetFixture(projectRoot: string): Promise<void> {
  await rm(resolve('.runtime/agent-provider-runtime-flow-test'), {
    recursive: true,
    force: true,
  });

  await mkdir(resolve(projectRoot, 'src'), {
    recursive: true,
  });

  await writeFile(
    resolve(projectRoot, 'package.json'),
    JSON.stringify(
      {
        name: 'agent-provider-runtime-flow-fixture',
        scripts: {
          typecheck: 'tsc --noEmit',
        },
        devDependencies: {
          typescript: '^5.7.2',
        },
      },
      null,
      2,
    ),
    'utf8',
  );

  await writeFile(
    resolve(projectRoot, 'tsconfig.json'),
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          strict: true,
        },
        include: ['src/**/*.ts'],
      },
      null,
      2,
    ),
    'utf8',
  );

  await writeFile(resolve(projectRoot, 'src/index.ts'), 'export const value = 1;\n', 'utf8');
}

main().catch((error: unknown) => {
  console.error(
    JSON.stringify(
      {
        status: 'failed',
        test: 'agent-provider-runtime-flow-test',
        error: error instanceof Error ? error.message : String(error),
      },
      null,
      2,
    ),
  );

  process.exitCode = 1;
});
