import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { CliRuntimeBridge } from '../cli/CliRuntimeBridge.js';
import { CliRunner } from '../cli/CliRunner.js';
import type {
  CliGitCommand,
  CliInspectCommand,
  CliRepairCommand,
  CliValidateCommand,
} from '../cli/CliTypes.js';

function assert(condition: boolean, message: string): void {
  if (!condition) {
    throw new Error(message);
  }
}

class RecordingCliRuntimeBridge extends CliRuntimeBridge {
  public readonly repairCommands: CliRepairCommand[] = [];

  public override inspect(command: CliInspectCommand): Promise<unknown> {
    return Promise.resolve({
      status: 'ok',
      projectName: command.projectName,
      objective: command.objective,
      inspection: {
        projectRoot: command.projectRoot,
        packageInfo: {
          name: 'cli-agent-provider-step-flow-fixture',
          scripts: {
            typecheck: 'tsc --noEmit',
          },
        },
        configInfo: {
          detectedStack: ['typescript'],
          hasPackageJson: true,
          hasTsconfig: true,
          hasEslintConfig: false,
          hasNextConfig: false,
          hasPrismaSchema: false,
        },
        targetFiles: command.targetFiles.map((relativePath) => {
          return {
            relativePath,
            exists: true,
            bytes: 24,
            extension: '.ts',
          };
        }),
      },
      issues: [],
      nextRecommendedActions: [],
    });
  }

  public override validate(command: CliValidateCommand): Promise<unknown> {
    return Promise.resolve({
      status: 'ok',
      projectName: command.projectName,
      objective: command.objective,
      inspection: {
        projectRoot: command.projectRoot,
      },
      validation: {
        status: 'passed',
        commands: [],
        findings: [],
      },
      issues: [],
      nextRecommendedActions: [],
    });
  }

  public override git(command: CliGitCommand): Promise<unknown> {
    return Promise.resolve({
      action: command.action,
      boundary: {
        branch: 'test-branch',
        workingTreeState: 'clean',
        clean: true,
        modifiedFiles: [],
        untrackedFiles: [],
        deletedFiles: [],
      },
      guard: {
        decision: 'allowed',
        allowed: true,
        reason: 'Test bridge allows git boundary.',
      },
      text: 'Git change boundary\nDecision: allowed',
    });
  }

  public override repair(command: CliRepairCommand): Promise<unknown> {
    this.repairCommands.push(command);

    return Promise.resolve({
      id: 'cli-agent-provider-step-flow-repair-attempt',
      status: 'proposal_ready',
      objective: command.objective,
      projectRoot: command.projectRoot,
      proposal: {
        id: 'cli-agent-provider-step-flow-proposal',
        summary: 'Controlled CLI provider step proposal.',
        riskLevel: 'low',
        operations: [
          {
            kind: 'replace_file',
            targetFile: 'src/index.ts',
            expectedCurrentContent: 'export const value = 1;\n',
            newContent: 'export const value = 1;\n',
            reason: 'Deterministic no-op proposal for CLI provider step flow.',
          },
        ],
        explanation: 'Generated by RecordingCliRuntimeBridge test double.',
      },
      patchValidation: {
        valid: true,
        issues: [],
      },
      diffPreviews: [
        {
          targetFile: 'src/index.ts',
          changed: false,
          changedLines: 0,
          markdown: '',
        },
      ],
      modelPolicyDecision: {
        allowed: true,
        status: 'allowed',
        provider: command.provider,
        selectedProvider: command.provider,
        selectedModel: command.providerModel ?? 'unknown',
        requiresPremiumApproval: false,
        estimate: {
          promptTokens: 0,
          completionTokens: command.estimatedCompletionTokens ?? 0,
          totalTokens: command.estimatedCompletionTokens ?? 0,
          estimatedUsd: 0,
          pricingKnown: false,
        },
        issues: [],
      },
      providerFallbackUsed: false,
      providerFallbackReason: undefined,
      gitBoundary: {
        safeToWriteLater: true,
        boundary: {
          branch: 'test-branch',
          workingTreeState: 'clean',
          clean: true,
          modifiedFiles: [],
          untrackedFiles: [],
          deletedFiles: [],
        },
        guard: {
          decision: 'allowed',
          allowed: true,
          reason: 'Test bridge allows write later.',
        },
      },
    });
  }
}

async function main(): Promise<void> {
  const fixtureRoot = resolve('.runtime/cli-agent-provider-step-flow-test/project');
  const targetFile = 'src/index.ts';
  const providerModel = 'poolside/laguna-xs.2:free';

  await resetFixture(fixtureRoot);

  const bridge = new RecordingCliRuntimeBridge();
  const runner = new CliRunner({
    bridge,
  });

  const blockedStart = await runner.run([
    'agent',
    'start',
    '--project',
    fixtureRoot,
    '--target',
    targetFile,
    '--name',
    'CLI Agent Provider Step Flow Fixture',
    '--objective',
    'This should be blocked because OpenRouter lacks explicit opt-in.',
    '--provider',
    'openrouter',
    '--model',
    providerModel,
  ]);

  assert(
    blockedStart.status === 'error',
    'CLI agent start with OpenRouter must fail without --allow-real-provider.',
  );
  assert(blockedStart.command === 'help', 'CLI parse failure should fallback to help command.');

  const startResult = await runner.run([
    'agent',
    'start',
    '--project',
    fixtureRoot,
    '--target',
    targetFile,
    '--name',
    'CLI Agent Provider Step Flow Fixture',
    '--objective',
    'Validate CLI agent provider flow without applying patches.',
    '--provider',
    'openrouter',
    '--allow-real-provider',
    '--model',
    providerModel,
    '--estimated-completion-tokens',
    '1200',
    '--include-project-memory',
  ]);

  assert(startResult.status === 'ok', 'CLI agent start with provider opt-in should pass.');
  assert(startResult.command === 'agent', 'Expected agent command.');

  const formattedStart = runner.format(startResult, 'text');

  assert(
    formattedStart.includes('Provider: openrouter'),
    'Formatted start output should show OpenRouter provider.',
  );
  assert(
    formattedStart.includes(`Model: ${providerModel}`),
    'Formatted start output should show provider model.',
  );
  assert(
    formattedStart.includes('Real provider enabled: yes'),
    'Formatted start output should show real provider opt-in.',
  );
  assert(
    formattedStart.includes('Project memory: yes'),
    'Formatted start output should show project memory flag.',
  );

  const statePath = resolve(fixtureRoot, '.runtime/agent-loop-state.json');
  const reportPath = resolve(fixtureRoot, '.runtime/agent-loop-report.md');

  const stateAfterStartRaw = await readFile(statePath, 'utf8');

  assert(
    stateAfterStartRaw.includes('"provider": "openrouter"'),
    'Agent state should persist requested provider.',
  );
  assert(
    stateAfterStartRaw.includes(`"providerModel": "${providerModel}"`),
    'Agent state should persist requested provider model.',
  );
  assert(
    stateAfterStartRaw.includes('"allowRealProvider": true'),
    'Agent state should persist allowRealProvider.',
  );
  assert(
    stateAfterStartRaw.includes('"includeProjectMemory": true'),
    'Agent state should persist includeProjectMemory.',
  );

  await runAgentStep(runner, fixtureRoot, 'inspect_project');
  await runAgentStep(runner, fixtureRoot, 'validate_project');
  await runAgentStep(runner, fixtureRoot, 'check_git');
  await runAgentStep(runner, fixtureRoot, 'build_repair_context');

  const stepResult = await runAgentStep(runner, fixtureRoot, 'request_repair_proposal');

  assert(stepResult.command === 'agent', 'Expected agent step command.');
  assert(bridge.repairCommands.length === 1, 'Expected one controlled repair command.');

  const repairCommand = requireRepairCommand(bridge);

  assert(repairCommand.provider === 'openrouter', 'Expected OpenRouter provider.');
  assert(repairCommand.providerModel === providerModel, 'Expected OpenRouter model.');
  assert(repairCommand.allowRealProvider === true, 'Expected real provider opt-in.');
  assert(repairCommand.includeProjectMemory === true, 'Expected project memory flag.');
  assert(repairCommand.estimatedCompletionTokens === 1200, 'Expected token estimate.');

  const formattedStep = runner.format(stepResult, 'text');

  assert(
    formattedStep.includes('Zero Runtime agent'),
    'Formatted step output should be human-readable agent output.',
  );
  assert(formattedStep.includes('Action: step'), 'Formatted step output should show step action.');

  const stateAfterStepRaw = await readFile(statePath, 'utf8');
  const reportRaw = await readFile(reportPath, 'utf8');

  assert(
    stateAfterStepRaw.includes('"execution_request_repair_proposal"'),
    'Agent state should persist request_repair_proposal execution.',
  );
  assert(
    stateAfterStepRaw.includes('"agentProviderAudit"'),
    'Agent state should persist agentProviderAudit.',
  );
  assert(
    stateAfterStepRaw.includes('"requestedProvider": "openrouter"'),
    'Agent provider audit should include requested OpenRouter provider.',
  );
  assert(
    stateAfterStepRaw.includes('"selectedProvider": "openrouter"'),
    'Agent provider audit should include selected OpenRouter provider.',
  );
  assert(
    stateAfterStepRaw.includes('"policyStatus": "allowed"'),
    'Agent provider audit should include allowed policy status.',
  );

  assert(
    !stateAfterStepRaw.includes('"execution_apply_patch"'),
    'Provider flow must not apply patch automatically.',
  );
  assert(
    !stateAfterStepRaw.includes('"approvalScope": "patch_apply"'),
    'Provider flow must not request patch approval automatically.',
  );

  const parsedState = parseJsonObject(stateAfterStepRaw, 'agent loop state');
  const approvals = requireArray(parsedState['approvals'], 'approvals');

  assert(approvals.length === 0, 'request_repair_proposal must not create approvals.');

  const actions = requireArray(parsedState['actions'], 'actions');
  const applyAction = requireRecordByStringField(
    actions,
    'id',
    'agent-action-apply_patch',
    'Expected apply_patch action.',
  );

  assert(
    applyAction['status'] === 'pending',
    'request_repair_proposal must not execute apply_patch.',
  );

  const finalContent = await readFile(resolve(fixtureRoot, targetFile), 'utf8');

  assert(
    finalContent === 'export const value = 1;\n',
    'CLI provider flow must not modify target file.',
  );

  assert(
    reportRaw.includes('Provider: openrouter'),
    'Agent report should include provider config.',
  );
  assert(
    reportRaw.includes(`Provider model: ${providerModel}`),
    'Agent report should include provider model.',
  );

  const jsonFormatted = runner.format(stepResult, 'json');

  assert(
    jsonFormatted.includes('"command": "agent"'),
    'JSON formatter should include agent command.',
  );

  console.info(
    JSON.stringify(
      {
        status: 'ok',
        test: 'cli-agent-provider-step-flow-test',
        statePath,
        reportPath,
      },
      null,
      2,
    ),
  );
}

async function runAgentStep(
  runner: CliRunner,
  projectRoot: string,
  stepKind: string,
): Promise<Awaited<ReturnType<CliRunner['run']>>> {
  const result = await runner.run(['agent', 'step', stepKind, '--project', projectRoot]);

  assert(result.status === 'ok', `Expected agent step ${stepKind} to pass.`);

  const state = parseAgentOutputState(result.output, stepKind);

  assert(
    !state.issues.some((issue) => issue.code === 'AGENT_ACTION_NOT_EXECUTABLE'),
    `Expected agent step ${stepKind} to be executable.`,
  );
  assert(
    !state.issues.some((issue) => issue.code === 'AGENT_STEP_EXECUTION_FAILED'),
    `Expected agent step ${stepKind} to execute without failure.`,
  );

  return result;
}

function parseAgentOutputState(
  output: unknown,
  stepKind: string,
): {
  issues: { code: string }[];
} {
  const record = requireRecord(output, `agent output for ${stepKind}`);
  const state = requireRecord(record['state'], `agent state for ${stepKind}`);
  const rawIssues = state['issues'];

  if (!Array.isArray(rawIssues)) {
    return {
      issues: [],
    };
  }

  return {
    issues: rawIssues
      .filter((issue): issue is Record<string, unknown> => {
        return isRecord(issue);
      })
      .flatMap((issue) => {
        const code = issue['code'];

        return typeof code === 'string' ? [{ code }] : [];
      }),
  };
}

function parseJsonObject(raw: string, label: string): Record<string, unknown> {
  const parsed = JSON.parse(raw) as unknown;

  return requireRecord(parsed, label);
}

function requireRepairCommand(bridge: RecordingCliRuntimeBridge): CliRepairCommand {
  const command = bridge.repairCommands[0];

  if (!command) {
    throw new Error('Expected repair command to be recorded.');
  }

  return command;
}

function requireRecord(value: unknown, label: string): Record<string, unknown> {
  if (!isRecord(value)) {
    throw new Error(`Expected object: ${label}`);
  }

  return value;
}

function requireArray(value: unknown, label: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new Error(`Expected array: ${label}`);
  }

  return value;
}

function requireRecordByStringField(
  values: readonly unknown[],
  field: string,
  expectedValue: string,
  message: string,
): Record<string, unknown> {
  for (const value of values) {
    if (!isRecord(value)) {
      continue;
    }

    if (value[field] === expectedValue) {
      return value;
    }
  }

  throw new Error(message);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

async function resetFixture(projectRoot: string): Promise<void> {
  await rm(resolve('.runtime/cli-agent-provider-step-flow-test'), {
    recursive: true,
    force: true,
  });

  await mkdir(resolve(projectRoot, 'src'), {
    recursive: true,
  });

  await writeFile(
    resolve(projectRoot, 'package.json'),
    JSON.stringify(
      {
        name: 'cli-agent-provider-step-flow-fixture',
        scripts: {
          typecheck: 'tsc --noEmit',
        },
        devDependencies: {
          typescript: '^5.7.2',
        },
      },
      null,
      2,
    ),
    'utf8',
  );

  await writeFile(
    resolve(projectRoot, 'tsconfig.json'),
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          strict: true,
        },
        include: ['src/**/*.ts'],
      },
      null,
      2,
    ),
    'utf8',
  );

  await writeFile(resolve(projectRoot, 'src/index.ts'), 'export const value = 1;\n', 'utf8');
}

main().catch((error: unknown) => {
  console.error(
    JSON.stringify(
      {
        status: 'failed',
        test: 'cli-agent-provider-step-flow-test',
        error: error instanceof Error ? error.message : String(error),
      },
      null,
      2,
    ),
  );

  process.exitCode = 1;
});
