import { Badge } from '../Badge';
import type { RuntimePatchProposalGenerateResult } from '../../types/runtime';

interface PatchSummaryProps {
  result: RuntimePatchProposalGenerateResult;
}

export function PatchSummary({ result }: PatchSummaryProps) {
  return (
    <article className="flex flex-col gap-4 p-5 rounded-xl border border-zinc-800/60 bg-zinc-950/50 shadow-sm">
      <div>
        <strong className="block text-sm font-semibold text-zinc-200">
          {result.proposal.summary}
        </strong>
        <p className="text-xs text-zinc-400 mt-1">
          Patch proposal generated by runtime. No files were applied.
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <Badge tone={result.proposal.status === 'rejected' ? 'red' : 'blue'}>
          {result.proposal.status}
        </Badge>
        <Badge tone={toneForRisk(result.proposal.riskLevel)}>
          risk: {result.proposal.riskLevel}
        </Badge>
        <Badge tone="yellow">
          approval: {result.proposal.requiresApproval ? 'required' : 'not required'}
        </Badge>
        <Badge tone="blue">{result.proposal.files.length} files</Badge>
      </div>
    </article>
  );
}

function toneForRisk(risk: RuntimePatchProposalGenerateResult['proposal']['riskLevel']) {
  if (risk === 'high') {
    return 'red';
  }

  if (risk === 'medium') {
    return 'yellow';
  }

  return 'green';
}
