import { Badge } from '../Badge';
import type { RuntimePatchProposalGenerateResult } from '../../types/runtime';

interface PatchSummaryProps {
  result: RuntimePatchProposalGenerateResult;
}

export function PatchSummary({ result }: PatchSummaryProps) {
  return (
    <article className="plan-summary-card">
      <div>
        <strong>{result.proposal.summary}</strong>
        <p className="muted">Patch proposal generated by runtime. No files were applied.</p>
      </div>

      <div className="plan-step-badges">
        <Badge tone={result.proposal.status === 'rejected' ? 'red' : 'blue'}>
          {result.proposal.status}
        </Badge>
        <Badge tone={toneForRisk(result.proposal.riskLevel)}>
          risk: {result.proposal.riskLevel}
        </Badge>
        <Badge tone="yellow">
          approval: {result.proposal.requiresApproval ? 'required' : 'not required'}
        </Badge>
        <Badge tone="blue">{result.proposal.files.length} files</Badge>
      </div>
    </article>
  );
}

function toneForRisk(risk: RuntimePatchProposalGenerateResult['proposal']['riskLevel']) {
  if (risk === 'high') {
    return 'red';
  }

  if (risk === 'medium') {
    return 'yellow';
  }

  return 'green';
}
